from DoubleLinkedList import Double_linked_list
inst_dll= Double_linked_list()
inst_dll.add_node_at_start("iron man")
inst_dll.add_node_at_start("hulk")
inst_dll.add_node_at_start("capitan america")
inst_dll.add_node_at_start("pantera negra")
print("lista inicio")
inst_dll.print_list()
print("\n")
inst_dll.add_node_at_end("doctor strange")
inst_dll.add_node_at_end("capitana marvel")
inst_dll.add_node_at_index("thor", 3)
inst_dll.add_node_at_end("bruja escarlata")
print("lista con todos añadidos")
inst_dll.print_list()
print("\n")
inst_dll.remove_at_start()
inst_dll.remove_at_end()
print("lista eliminando elementos al inicio y al final")
inst_dll.print_list()
print("\n")
inst_dll.remove_node_at_index(2)
print("eliminado a posicion 2")
inst_dll.print_list()
print("\n")
inst_dll.remove_node_by_value("iron man")
inst_dll.print_list()
print("\n")
inst_dll.get_node_at_index(3)
inst_dll.update_node_at_value("hulk", "spider man")
inst_dll.update_node_at_index(3,"soldado del invierno")
inst_dll.print_list()
print("\n")
print("lista ordenada")
inst_dll.sort_asc()
inst_dll.print_list()
print("\n")
inst_dll.add_node_at_index("soldado del invierno", 3)
inst_dll.add_node_at_index("capitana marvel",2)
inst_dll.print_list()
print("\n")
print("duplicados")
inst_dll.has_duplicates()
inst_dll.has_dupicaltes_with_information()
print("composicion")
inst_dll.calculate_complexity(inst_dll.add_node_at_start)

